### ISSUE TITLE
可以指定生成的HASH值文件的文件名称吗

### ISSUE THREAD

**Issue by hellozrh** [tavenli/FileHashGen#1]
1. 可以指定生成的HASH值文件的文件名称吗
2. 比如我指定只生成MD5的内容，则生成的MD5文件名称可以指定，且文件内容只有MD5值。
3. 
类似于下面那种
```shell
FileHashGen.exe -f path_to_file.zip -c SHA-256 -o path_to_file.zip.sha256
```
运行结束后，生成文件path_to_file.zip.sha256，文件中只有sha-256内容，方便读取出来检查验证。

**Comment by tavenli** [comment]
指定输出结果文件的文件名：
FileHashGen.exe -f test.zip -c “SHA-256” -o report.txt

指定输出结果文件的文件名（内容仅含hash值）：
FileHashGen.exe -f test.zip -c “SHA-256” -ot "only-hash" -o test.zip.sha256

已增加上面的命令参数支持

**Comment by hellozrh** [comment]
@tavenli 非常感谢支持，目前生成sha256倒是非常方便，可以生成sha256内容到指定文件，并做后续校验，感谢感谢。
还有一个小小的请求，就是命令执行完成后，非要输入enter才会退出，不利于在jenkins中自动化校验。方便最后去掉这个enter才结束进程吗？另外，日志里输出的版本号还是V1.0，这也算个小ｂｕｇ，不影响使用。

![image](https://github.com/tavenli/FileHashGen/assets/12250931/1c40dbfb-800f-4b8c-a576-01eb67af3e35)
![image](https://github.com/tavenli/FileHashGen/assets/12250931/d0fc8ec8-e78c-4ce8-bfc7-0bd5f2987eac)

**Comment by tavenli** [comment]
已去掉需要按 Enter键才能退出，新版本代码已提交，用新的版本即可

**Comment by hellozrh** [comment]
> 已去掉需要按 Enter键才能退出，新版本代码已提交，用新的版本即可

问题已经解决，非常感谢 @tavenli
